
export const DI_TOKENS = {
    WALLET_SERVICE: 'WALLET_SERVICE',
    IPFS_SERVICE: 'IPFS_SERVICE',
    CONTRACT_SERVICE: 'CONTRACT_SERVICE',
    CONFIG_SERVICE: 'CONFIG_SERVICE',
    ACCOUNT_VM: 'ACCOUNT_VM',
}